import type { PriceType } from '@/db/schema'

export interface DemoSeller {
  name: string
  email: string
}

export const DEMO_SELLERS: DemoSeller[] = [
  { name: 'Jana Dvořáková', email: 'jana@safebazos.test' },
  { name: 'Petr Novotný', email: 'petr@safebazos.test' },
  { name: 'Lucie Králová', email: 'lucie@safebazos.test' },
  { name: 'Tomáš Černý', email: 'tomas@safebazos.test' },
]

export interface DemoListing {
  /** „hlavní-kategorie/podkategorie“ */
  category: string
  title: string
  description: string
  priceType: PriceType
  priceAmount?: number
  postalCode: string
  city: string
  phone?: string
  acceptsSafePayment: boolean
  sellerIndex: number
  daysAgo: number
}

export const DEMO_LISTINGS: DemoListing[] = [
  {
    category: 'auto/skoda',
    title: 'Škoda Octavia III Combi 2.0 TDI, 2017',
    description:
      'Prodám Škodu Octavii Combi 2.0 TDI 110 kW, rok 2017, najeto 168 000 km. Servisní knížka, druhý majitel, STK do 2027. Nová rozvodová sada a brzdy. Možnost prohlídky v servisu.',
    priceType: 'amount',
    priceAmount: 289000,
    postalCode: '60200',
    city: 'Brno',
    phone: '777123456',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 1,
  },
  {
    category: 'auto/pneumatiky-kola',
    title: 'Zimní pneumatiky Michelin 205/55 R16 na discích',
    description:
      'Sada 4 zimních pneu Michelin Alpin 6, vzorek 6 mm, na plechových discích 5x112. Sezónu jeté, uskladněné v garáži. Pasuje na Octavii, Golf, Leon.',
    priceType: 'amount',
    priceAmount: 6500,
    postalCode: '11000',
    city: 'Praha',
    acceptsSafePayment: true,
    sellerIndex: 3,
    daysAgo: 3,
  },
  {
    category: 'auto/volkswagen',
    title: 'VW Golf VII 1.4 TSI Highline',
    description:
      'Golf 7 Highline, benzín 1.4 TSI 92 kW, 2015, 124 000 km. Kožené sedačky, navigace, výhřev, parkovací senzory. Nehavarováno, doložím Cebia.',
    priceType: 'amount',
    priceAmount: 229000,
    postalCode: '37001',
    city: 'České Budějovice',
    phone: '602987654',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 5,
  },
  {
    category: 'mobily/apple',
    title: 'iPhone 14 128 GB Midnight, baterie 91 %',
    description:
      'Prodám iPhone 14 128 GB v barvě Midnight. Kondice baterie 91 %, bez škrábanců, vždy v obalu a se sklem. Originální krabice a kabel. Doklad o koupi z Alzy.',
    priceType: 'amount',
    priceAmount: 11900,
    postalCode: '70030',
    city: 'Ostrava',
    phone: '731555222',
    acceptsSafePayment: true,
    sellerIndex: 0,
    daysAgo: 0,
  },
  {
    category: 'mobily/samsung',
    title: 'Samsung Galaxy S23 256 GB, zelený',
    description:
      'Samsung Galaxy S23 256 GB, rok starý, plně funkční, drobné oděrky na rámečku. K telefonu přidám dva kryty. Předání osobně v Plzni nebo pošlu s ochranou platby.',
    priceType: 'amount',
    priceAmount: 12500,
    postalCode: '30100',
    city: 'Plzeň',
    acceptsSafePayment: true,
    sellerIndex: 2,
    daysAgo: 2,
  },
  {
    category: 'mobily/chytre-hodinky',
    title: 'Apple Watch Series 8 45 mm GPS',
    description:
      'Hodinky Apple Watch Series 8, 45 mm, GPS verze, pouzdro hliník. Baterie 94 %. Dva řemínky navíc (sportovní a milánský tah).',
    priceType: 'amount',
    priceAmount: 6900,
    postalCode: '50002',
    city: 'Hradec Králové',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 6,
  },
  {
    category: 'pc/notebooky',
    title: 'MacBook Air M2 13" 8/256 GB',
    description:
      'MacBook Air s čipem M2, 8 GB RAM, 256 GB SSD, barva Space Gray. 142 cyklů baterie, displej bez vad. Na záruce do 03/2027. Prodávám kvůli přechodu na větší model.',
    priceType: 'amount',
    priceAmount: 21900,
    postalCode: '12000',
    city: 'Praha',
    phone: '739111333',
    acceptsSafePayment: true,
    sellerIndex: 0,
    daysAgo: 1,
  },
  {
    category: 'pc/komponenty',
    title: 'Grafická karta RTX 3070 8 GB',
    description:
      'NVIDIA GeForce RTX 3070 Founders Edition. Netěženo, pouze hraní. Čištěno a vyměněné teplovodivé pasty. Záruka již vypršela.',
    priceType: 'amount',
    priceAmount: 7200,
    postalCode: '77900',
    city: 'Olomouc',
    acceptsSafePayment: true,
    sellerIndex: 3,
    daysAgo: 4,
  },
  {
    category: 'pc/monitory',
    title: 'Monitor Dell 27" QHD 144 Hz',
    description:
      'Herní monitor Dell S2721DGF, 27", 2560×1440, 165 Hz, IPS. Bez vadných pixelů, s původním stojanem a DisplayPort kabelem.',
    priceType: 'amount',
    priceAmount: 5400,
    postalCode: '46001',
    city: 'Liberec',
    acceptsSafePayment: false,
    sellerIndex: 2,
    daysAgo: 8,
  },
  {
    category: 'sport/kola',
    title: 'Horské kolo Author Solution 29", vel. L',
    description:
      'Prodám horské kolo Author Solution 29", rám L, Shimano Deore 1×12, vzduchová vidlice RockShox. Najeto cca 1 500 km, pravidelný servis, nové pláště.',
    priceType: 'amount',
    priceAmount: 18500,
    postalCode: '60200',
    city: 'Brno',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 2,
  },
  {
    category: 'sport/zimni-sporty',
    title: 'Sjezdové lyže Atomic Redster 170 cm s vázáním',
    description:
      'Lyže Atomic Redster X5, délka 170 cm, vázání Atomic M10. Po servisu (broušení, voskování). Vhodné pro mírně pokročilé.',
    priceType: 'amount',
    priceAmount: 3900,
    postalCode: '54301',
    city: 'Vrchlabí',
    acceptsSafePayment: false,
    sellerIndex: 2,
    daysAgo: 12,
  },
  {
    category: 'sport/fitness',
    title: 'Činky jednoruční 2× 20 kg, nakládací',
    description:
      'Nakládací jednoruční činky, osy s maticemi, celkem 40 kg litinových kotoučů. Osobní odběr, poštou kvůli váze neposílám.',
    priceType: 'amount',
    priceAmount: 1800,
    postalCode: '14000',
    city: 'Praha',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 7,
  },
  {
    category: 'deti/kocarky',
    title: 'Kočárek Cybex Priam kombinovaný 2v1',
    description:
      'Kombinovaný kočárek Cybex Priam, hluboká korba i sportovní sedačka, barva Deep Black. Používaný u jednoho dítěte, pravidelně čištěný. Pláštěnka a taška zdarma.',
    priceType: 'amount',
    priceAmount: 14900,
    postalCode: '37001',
    city: 'České Budějovice',
    acceptsSafePayment: true,
    sellerIndex: 0,
    daysAgo: 3,
  },
  {
    category: 'deti/hracky',
    title: 'LEGO Technic 42115 Lamborghini Sián – kompletní',
    description:
      'LEGO Technic Lamborghini Sián FKP 37, set 42115. Kompletní včetně návodů a krabice, jednou postaveno a vystaveno ve vitríně.',
    priceType: 'amount',
    priceAmount: 7400,
    postalCode: '50002',
    city: 'Hradec Králové',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 9,
  },
  {
    category: 'deti/autosedacky',
    title: 'Autosedačka Britax Römer 9–18 kg Isofix',
    description:
      'Autosedačka Britax Römer Trifix 2 i-Size, Isofix, nebourané, potah vypraný. Posílám Zásilkovnou nebo osobně v Kolíně.',
    priceType: 'amount',
    priceAmount: 3200,
    postalCode: '28002',
    city: 'Kolín',
    acceptsSafePayment: true,
    sellerIndex: 2,
    daysAgo: 4,
  },
  {
    category: 'nabytek/sedaci-soupravy',
    title: 'Rohová sedačka rozkládací s úložným prostorem',
    description:
      'Rohová sedací souprava, šedá látka, rozměr 260×180 cm, rozkládací na spaní, úložný prostor. Nekuřácká domácnost bez zvířat. Nutný vlastní odvoz.',
    priceType: 'amount',
    priceAmount: 4500,
    postalCode: '61200',
    city: 'Brno',
    acceptsSafePayment: false,
    sellerIndex: 0,
    daysAgo: 6,
  },
  {
    category: 'nabytek/stoly-zidle',
    title: 'Jídelní stůl dub masiv + 4 židle',
    description:
      'Jídelní stůl z dubového masivu 160×90 cm a čtyři čalouněné židle. Stůl má drobné stopy používání, židle jako nové.',
    priceType: 'negotiable',
    postalCode: '77900',
    city: 'Olomouc',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 10,
  },
  {
    category: 'dum-a-zahrada/zahrada',
    title: 'Sekačka Honda HRG 466 s pojezdem',
    description:
      'Benzínová sekačka Honda HRG 466 SK s pojezdem, záběr 46 cm, koš 55 l. Pravidelně servisovaná, nový olej a nůž.',
    priceType: 'amount',
    priceAmount: 5900,
    postalCode: '39701',
    city: 'Písek',
    phone: '604222111',
    acceptsSafePayment: false,
    sellerIndex: 1,
    daysAgo: 5,
  },
  {
    category: 'dum-a-zahrada/stavebni-material',
    title: 'Zámková dlažba 30 m², zbytek ze stavby',
    description:
      'Zbylá zámková dlažba Best Klasiko, přírodní, tloušťka 6 cm, cca 30 m² na paletách. Odvoz vlastní, pomohu naložit.',
    priceType: 'offer',
    postalCode: '25101',
    city: 'Říčany',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 14,
  },
  {
    category: 'elektro/herni-konzole',
    title: 'PlayStation 5 s mechanikou + 2 ovladače',
    description:
      'PS5 disková verze, dva ovladače DualSense, hry Spider-Man 2 a FIFA 24. Konzole čištěná, bez závad, originální krabice.',
    priceType: 'amount',
    priceAmount: 9900,
    postalCode: '70030',
    city: 'Ostrava',
    acceptsSafePayment: true,
    sellerIndex: 3,
    daysAgo: 1,
  },
  {
    category: 'elektro/televize',
    title: 'Televize LG OLED 55" C1',
    description:
      'LG OLED55C1, 4K, 120 Hz, HDMI 2.1 – ideální na hraní. Bez vypálených pixelů, dálkové ovládání Magic Remote. Pouze osobní převzetí.',
    priceType: 'amount',
    priceAmount: 16900,
    postalCode: '11000',
    city: 'Praha',
    acceptsSafePayment: true,
    sellerIndex: 0,
    daysAgo: 11,
  },
  {
    category: 'elektro/domaci-spotrebice',
    title: 'Pračka Bosch 8 kg, A+++',
    description:
      'Předem plněná pračka Bosch Serie 6, 8 kg, 1400 ot., tichý invertorový motor. Stáří 3 roky, důvod prodeje stěhování.',
    priceType: 'amount',
    priceAmount: 6200,
    postalCode: '60200',
    city: 'Brno',
    acceptsSafePayment: false,
    sellerIndex: 2,
    daysAgo: 2,
  },
  {
    category: 'foto/fotoaparaty',
    title: 'Sony A7 III tělo, 18 000 cvaků',
    description:
      'Bezzrcadlovka Sony Alpha 7 III, pouze tělo, 18 tisíc expozic. Dvě baterie, nabíječka, krabice. Senzor čistý.',
    priceType: 'amount',
    priceAmount: 27900,
    postalCode: '12000',
    city: 'Praha',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 3,
  },
  {
    category: 'hudba/kytary',
    title: 'Elektrická kytara Fender Stratocaster Player',
    description:
      'Fender Player Stratocaster, Mexiko, barva Polar White, hmatník javor. Nové struny, seřízená. Včetně gigbagu.',
    priceType: 'amount',
    priceAmount: 16500,
    postalCode: '30100',
    city: 'Plzeň',
    acceptsSafePayment: true,
    sellerIndex: 2,
    daysAgo: 7,
  },
  {
    category: 'hudba/cd-lp',
    title: 'Sbírka LP desek – česká rocková scéna',
    description:
      'Soubor 40 LP desek (Olympic, Pražský výběr, Katapult, Žlutý pes…). Stav vinylů VG+ až NM, seznam pošlu zprávou.',
    priceType: 'in_text',
    postalCode: '46001',
    city: 'Liberec',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 15,
  },
  {
    category: 'zvirata/chovatelske-potreby',
    title: 'Přepravka pro psa vel. L + pelíšek',
    description:
      'Plastová přepravka pro psa velikost L (vhodná do letadla) a velký pelíšek 100 cm. Obojí čisté, pes vyrostl.',
    priceType: 'amount',
    priceAmount: 1200,
    postalCode: '53002',
    city: 'Pardubice',
    acceptsSafePayment: false,
    sellerIndex: 0,
    daysAgo: 9,
  },
  {
    category: 'zvirata/akvaristika',
    title: 'Akvárium 120 l kompletní s filtrem',
    description:
      'Akvárium 80×35×45 cm s krytem, LED osvětlením, vnějším filtrem Eheim a topítkem. Bez ryb, vhodné pro začátečníky.',
    priceType: 'amount',
    priceAmount: 2500,
    postalCode: '53002',
    city: 'Pardubice',
    acceptsSafePayment: false,
    sellerIndex: 2,
    daysAgo: 13,
  },
  {
    category: 'knihy/beletrie',
    title: 'Harry Potter 1–7, české vydání Albatros',
    description:
      'Kompletní série Harry Potter v češtině, nakladatelství Albatros, pevná vazba. Čtené jednou, bez poškození.',
    priceType: 'amount',
    priceAmount: 1400,
    postalCode: '66902',
    city: 'Znojmo',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 4,
  },
  {
    category: 'knihy/ucebnice',
    title: 'Učebnice matematiky pro gymnázia – komplet',
    description:
      'Sada učebnic Matematika pro gymnázia (Prometheus), 8 dílů, s poznámkami tužkou. Vhodné k maturitě.',
    priceType: 'amount',
    priceAmount: 600,
    postalCode: '58601',
    city: 'Jihlava',
    acceptsSafePayment: false,
    sellerIndex: 0,
    daysAgo: 16,
  },
  {
    category: 'obleceni/panske',
    title: 'Pánská zimní bunda The North Face, vel. M',
    description:
      'Péřová bunda The North Face McMurdo, velikost M, černá. Nošená dvě zimy, bez poškození, originál s visačkou.',
    priceType: 'amount',
    priceAmount: 3500,
    postalCode: '14000',
    city: 'Praha',
    acceptsSafePayment: true,
    sellerIndex: 3,
    daysAgo: 2,
  },
  {
    category: 'obleceni/obuv',
    title: 'Dámské boty Nike Air Max 90, vel. 38',
    description:
      'Tenisky Nike Air Max 90, velikost 38, bílo-růžové. Nošené párkrát, jako nové. Pošlu Zásilkovnou.',
    priceType: 'amount',
    priceAmount: 1600,
    postalCode: '76001',
    city: 'Zlín',
    acceptsSafePayment: true,
    sellerIndex: 2,
    daysAgo: 1,
  },
  {
    category: 'reality/byty',
    title: 'Pronájem bytu 2+kk, 54 m², Brno-Královo Pole',
    description:
      'Nabízím k pronájmu byt 2+kk v novostavbě, 54 m², balkon, sklep, parkovací stání. Nájem 17 500 Kč + energie. Volné od listopadu, prohlídky po domluvě.',
    priceType: 'amount',
    priceAmount: 17500,
    postalCode: '61200',
    city: 'Brno',
    phone: '775444888',
    acceptsSafePayment: false,
    sellerIndex: 0,
    daysAgo: 3,
  },
  {
    category: 'prace/brigady',
    title: 'Brigáda – pomoc při sklizni jablek, víkendy',
    description:
      'Hledáme brigádníky na sklizeň jablek v sadu u Litoměřic, září–říjen o víkendech. 180 Kč/h, občerstvení zajištěno.',
    priceType: 'in_text',
    postalCode: '41201',
    city: 'Litoměřice',
    acceptsSafePayment: false,
    sellerIndex: 1,
    daysAgo: 5,
  },
  {
    category: 'sluzby/stehovani',
    title: 'Stěhování a vyklízení – Praha a okolí',
    description:
      'Nabízím stěhování bytů, převoz nábytku a vyklízení. Dodávka 3,5 t, dva pracovníci. Cena podle rozsahu, nezávazná kalkulace zdarma.',
    priceType: 'negotiable',
    postalCode: '15000',
    city: 'Praha',
    phone: '608777999',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 6,
  },
  {
    category: 'motorky/skutry',
    title: 'Skútr Honda PCX 125, 2020',
    description:
      'Honda PCX 125, rok 2020, najeto 9 800 km. Garážovaný, servis v autorizovaném servisu, horní kufr Givi. STK platná.',
    priceType: 'amount',
    priceAmount: 54000,
    postalCode: '30100',
    city: 'Plzeň',
    acceptsSafePayment: true,
    sellerIndex: 1,
    daysAgo: 8,
  },
  {
    category: 'stroje/naradi',
    title: 'Aku vrtačka Makita 18V + 2 baterie',
    description:
      'Aku příklepová vrtačka Makita DHP484, dvě baterie 5 Ah, nabíječka, kufr Makpac. Plně funkční.',
    priceType: 'amount',
    priceAmount: 4200,
    postalCode: '70030',
    city: 'Ostrava',
    acceptsSafePayment: true,
    sellerIndex: 0,
    daysAgo: 2,
  },
  {
    category: 'vstupenky/koncerty',
    title: '2× vstupenka Coldplay – nemohu jet',
    description:
      'Prodám dvě vstupenky na stání. Přepis vstupenek přes oficiální systém pořadatele, cena jako nákupní. Více info ve zprávě.',
    priceType: 'amount',
    priceAmount: 4800,
    postalCode: '11000',
    city: 'Praha',
    acceptsSafePayment: true,
    sellerIndex: 2,
    daysAgo: 1,
  },
  {
    category: 'ostatni/sberatelstvi',
    title: 'Sbírka pohlednic z let 1920–1950',
    description:
      'Přes 200 pohlednic z českých měst, převážně prošlé poštou. Prodávám jako celek. Více fotek na www.moje-sbirka-pohlednic.cz nebo pište na WhatsApp.',
    priceType: 'offer',
    postalCode: '50002',
    city: 'Hradec Králové',
    acceptsSafePayment: false,
    sellerIndex: 1,
    daysAgo: 10,
  },
  {
    // Ukázka zadrženého inzerátu pro moderaci (phishing odkaz + žádost o kartu).
    category: 'mobily/apple',
    title: 'iPhone 15 Pro Max NOVÝ – super cena',
    description:
      'Nový nerozbalený iPhone 15 Pro Max. Platba přes bezpečnou platbu na https://bazos-platba.online/overeni, pro odeslání peněz potřebuji číslo vaší karty.',
    priceType: 'amount',
    priceAmount: 9900,
    postalCode: '11000',
    city: 'Praha',
    acceptsSafePayment: false,
    sellerIndex: 3,
    daysAgo: 0,
  },
]
